name: 'tag'
on:
  push:
    branches:
      - develop
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        #version_assertion_command: 'grep -q "\"version\": \"$version\"" package.json'
        version_assertion_command: 'cat VERSION.py | awk -F= \'{print $2}\' | sed \"s/\'//g\"'
